# Generated by Django 5.2.8 on 2025-11-13 18:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Formulario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "pub_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="fecha de publicación",
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        default=7, help_text="Duración del formulario en días."
                    ),
                ),
                (
                    "propietario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formularios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnvioFormulario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_envio",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="envios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "formulario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="envios",
                        to="votacion.formulario",
                    ),
                ),
            ],
            options={
                "unique_together": {("formulario", "usuario")},
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pregunta_texto",
                    models.CharField(
                        max_length=500, verbose_name="texto de la pregunta"
                    ),
                ),
                (
                    "tipo_pregunta",
                    models.CharField(
                        choices=[
                            ("CHOICE", "Opción Múltiple"),
                            ("TEXT", "Respuesta Abierta"),
                        ],
                        default="CHOICE",
                        max_length=10,
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "formulario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preguntas",
                        to="votacion.formulario",
                    ),
                ),
            ],
            options={
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice_text",
                    models.CharField(max_length=200, verbose_name="texto de la opción"),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opciones",
                        to="votacion.question",
                    ),
                ),
            ],
            options={
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="Respuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("respuesta_texto", models.TextField(blank=True, null=True)),
                (
                    "envio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas",
                        to="votacion.envioformulario",
                    ),
                ),
                (
                    "opcion_seleccionada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="votacion.choice",
                    ),
                ),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas",
                        to="votacion.question",
                    ),
                ),
            ],
        ),
    ]
