# Generated by Django 5.2.8 on 2025-11-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envioformulario',
            name='datos_cifrados',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
